experiments:
- bearing: -45
  dist: 3
  v0: 0.0
- bearing: 0
  dist: 3
  v0: 0.0
- bearing: 45
  dist: 3
  v0: 0.0
- bearing: -45
  dist: 9
  v0: 0.0
- bearing: 0
  dist: 9
  v0: 0.0
- bearing: 45
  dist: 9
  v0: 0.0
- bearing: -45
  dist: 3
  v0: 1.0
- bearing: 0
  dist: 3
  v0: 1.0
- bearing: 45
  dist: 3
  v0: 1.0
- bearing: -45
  dist: 9
  v0: 1.0
- bearing: 0
  dist: 9
  v0: 1.0
- bearing: 45
  dist: 9
  v0: 1.0
