v0: 0.5
frame_id: "world"
offset: [10, 0]
waypoints:
  - [0, 0]
  - [5, 0]
  - [10, 0]
  - [15, 0]
  - [20, 0]
  - [25, 0]
  - [30, 0]
  - [30, 5]
  - [25, 5]
  - [20, 5]
  - [15, 5]
  - [10, 5]
  - [5, 5]
  - [0, 5]
  - [0, 10]
  - [5, 10]
  - [10, 10]
  - [15, 10]
  - [20, 10]
  - [25, 10]
  - [30, 10]
  - [30, 15]
  - [25, 15]
  - [20, 15]
  - [15, 15]
  - [10, 15]
  - [5, 15]
  - [0, 15]
simulated_waste:
  - [2.5, 1.5]
  - [7.1, 0.1]
  - [17.9, 2.2]
  - [12.3, 7.8]
  - [25.0, 14.5]

