- experiment_name: acceleration_1.0
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 1.0
    tr: 1.0
  - duration: 20.0
    tl: 1.0
    tr: 1.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: acceleration_0.8
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.8
    tr: 0.8
  - duration: 20.0
    tl: 0.8
    tr: 0.8
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: acceleration_0.6
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.6
    tr: 0.6
  - duration: 20.0
    tl: 0.6
    tr: 0.6
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: acceleration_0.4
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.4
    tr: 0.4
  - duration: 20.0
    tl: 0.4
    tr: 0.4
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: rotation_1.0
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.5762
    tr: -1.0
  - duration: 20.0
    tl: 0.5762
    tr: -1.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: rotation_0.8
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.519
    tr: -0.8
  - duration: 20.0
    tl: 0.519
    tr: -0.8
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: rotation_0.6
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.4529
    tr: -0.6
  - duration: 20.0
    tl: 0.4529
    tr: -0.6
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: circle_left_1.0
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.0
    tr: 1.0
  - duration: 20.0
    tl: 0.0
    tr: 1.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: circle_right_1.0
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 1.0
    tr: 0.0
  - duration: 20.0
    tl: 1.0
    tr: 0.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: zigzag_1.0
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 1.0
    tr: 1.0
  - duration: 3.0
    tl: 1.0
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 1.0
  - duration: 3.0
    tl: 1.0
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 1.0
  - duration: 3.0
    tl: 1.0
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 1.0
  - duration: 3.0
    tl: 1.0
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 1.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: acceleration_0.9
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.9
    tr: 0.9
  - duration: 20.0
    tl: 0.9
    tr: 0.9
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: acceleration_0.7
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.7
    tr: 0.7
  - duration: 20.0
    tl: 0.7
    tr: 0.7
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: acceleration_0.5
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.5
    tr: 0.5
  - duration: 20.0
    tl: 0.5
    tr: 0.5
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: rotation_0.9
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.5456
    tr: -0.9
  - duration: 20.0
    tl: 0.5456
    tr: -0.9
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: rotation_0.7
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.4857
    tr: -0.7
  - duration: 20.0
    tl: 0.4857
    tr: -0.7
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: circle_left_0.8
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.0
    tr: 0.8
  - duration: 20.0
    tl: 0.0
    tr: 0.8
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: circle_right_0.8
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.8
    tr: 0.0
  - duration: 20.0
    tl: 0.8
    tr: 0.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: circle_left_0.6
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.0
    tr: 0.6
  - duration: 20.0
    tl: 0.0
    tr: 0.6
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: circle_right_0.6
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.6
    tr: 0.0
  - duration: 20.0
    tl: 0.6
    tr: 0.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: backwards_1.0
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: -1.0
    tr: -1.0
  - duration: 20.0
    tl: -1.0
    tr: -1.0
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: backwards_0.8
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: -0.8
    tr: -0.8
  - duration: 20.0
    tl: -0.8
    tr: -0.8
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: backwards_0.6
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: -0.6
    tr: -0.6
  - duration: 20.0
    tl: -0.6
    tr: -0.6
  - duration: 10.0
    tl: 0.0
    tr: 0.0
- experiment_name: zigzag_0.6
  sections:
  - duration: 5.0
    tl: 0.0
    tr: 0.0
  - duration: 10.0
    tl: 0.6
    tr: 0.6
  - duration: 3.0
    tl: 0.6
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 0.6
  - duration: 3.0
    tl: 0.6
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 0.6
  - duration: 3.0
    tl: 0.6
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 0.6
  - duration: 3.0
    tl: 0.6
    tr: 0.0
  - duration: 3.0
    tl: 0.0
    tr: 0.6
  - duration: 10.0
    tl: 0.0
    tr: 0.0
